version: 2
companion_workflows:
  - .github/workflows/ci.yml
  - .github/workflows/release.yml
  - .github/workflows/reusable-build.yml
pipelines:
  ci:
    stages:
      - id: test
        workflow: .github/workflows/stage-test.yml
        outputs:
          - version
          - git_sha
          - snapshot_run_id

      - id: build
        workflow: .github/workflows/stage-build.yml
        needs:
          - test
        inputs:
          version: ${{ context.test.version }}
          git_sha: ${{ context.test.git_sha }}
