name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  actions: write
  statuses: write

jobs:
  run-pipeline:
    name: Run CI pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: aeswibon/pipeline-compose-run@v1.17.1
        with:
          pipeline_file: .github/pipelines/ci.yml
          github_token: ${{ github.token }}
          ref: ${{ github.head_ref || github.ref_name }}
